### ISSUE TITLE
can't find the downloaded subtitles

### ISSUE THREAD

**Issue by Fallast** [davidde/mpv-autosub#13]
im new to github so i wasn't sure if i should ask this here, as i said in the title, i don't know where the subtitles are located, i thoguht they would be in the same directory where the video file is but it isn't

**Comment by davidde** [comment]
Yes, they should appear next to the video file. Did you get an in-video message about subtitles when starting the video?

**Comment by Fallast** [comment]
well they are not appearing next to the video file, they are being 
downloaded and works but i can't see them inside the directory

**Comment by davidde** [comment]
That is very weird. Are you sure subtitles were downloaded? If your video file has embedded subtitles, the script will just activate those instead of downloading other subtitles.

Anyway, running MPV from the terminal with [debug](https://github.com/davidde/mpv-autosub/blob/master/autosub.lua#L47) set to true should tell you where they are saved.

**Comment by Fallast** [comment]
nevermind sorry i was wrong, does autosub find subtitles by hash? because
it can't seem to find the subtitles for some films i have, maybe I'm doing
something wrong

**Comment by davidde** [comment]
No, it's definitely not flawless; rare movies or rare releases will have trouble finding anything.
Autosub uses [subliminal download](https://subliminal.readthedocs.io/en/latest/user/cli.html#subliminal-download) internally; check their [scoring documentation](https://subliminal.readthedocs.io/en/latest/user/how_it_works.html#scoring) to find out how that works.
