### ISSUE TITLE
No subtitles found

### ISSUE THREAD

**Issue by Shirobachi** [davidde/mpv-autosub#16]
I cannot download any subtitles ;/ Everytime is no English subtitles found, 

my config file: https://pastebin.com/8xcC4ngp
Debug: https://pastebin.com/W7bdRyeh

**Comment by davidde** [comment]
Here's a few quick ideas:
* Fix your `mpv.conf`: Remove the unparseable extra characters: `: jpn, jp, en`.
* `Can't load unknown script: /home/shirobachi/.config/mpv/scripts/.autosub.lua.swp`: Rename the script to the more conventional `autosub.lua`.
* Comment out the provider line again, to check if it's related to that.

**Comment by Shirobachi** [comment]
What I changed? 
- empty `mpv.conf` (i was coppied from some tutorial Ill have fun w/ conf another time)
- file `.autosub.lua.swp` was probably made by vim (terminal editor) I just deleted this file not in script dir is ONLY file with script what is that repo about
- commented credentials to providers
Now I do not see the error, just after some time like 15 second test searching subs dissapear (subs not dl)

My conf: https://pastebin.com/pCAgdYER
Debug output: https://pastebin.com/c9XCXtm8
Debug after uncomment provider: https://pastebin.com/R8vQSZKM

Thanks for help! <3

**Comment by davidde** [comment]
Remove the `log(a)` you added on line 102.

`a` is a table data structure, and cannot be passed to a function that requires a string.

**Comment by Shirobachi** [comment]
Oh right, I forgot ;/

Debug: https://pastebin.com/RNNSuTx3
conf: https://pastebin.com/U0f0w88K

**Comment by davidde** [comment]
The script is working as it should now. As you can see in the debug output, the problem lies with subliminal.

Like I suggested before, try different setups, e.g. without the provider line, with other video files, etc. And stop vim from creating swap files where mpv will try to pick them up.

I recommend fixing subliminal first by running without the autosub script, and reaching out to the subliminal folks if you can't get it to work.

**Comment by Shirobachi** [comment]
Okay, thank you so much <3

**Comment by Shirobachi** [comment]
Just wanted to inform that I resolved problem, it was my password with some illegal characters. Now I using only chars a-Z0-9 and it work perfectlly :)

**Comment by davidde** [comment]
Glad you got it working. This is exactly why I suggested running without the provider line; a less frequently used feature like this is the more obvious place where things could go wrong.

Out of curiosity, did this password work on the Opensubtitles website itself? Do they allow some rather uncommon Unicode characters in their password field?

**Comment by Shirobachi** [comment]
Yes I logged in to Opensubtitles by browser. 
At first I tried with no providers but it didn't work probably by my fault :D 

Anyway thanks for your work <3

**Comment by davidde** [comment]
Happy to help.

Anyways, if you can confirm there are specific passwords that do not work with this script, but do work with the subliminal command line tool (without script), I can consider passing the password as unicode to subliminal. Since this is very much an edge case, I won't bother doing this unless someone specifically requests it.

**Comment by Shirobachi** [comment]
TBH I cannot confirm for sure, but while I was struggling with the script you suggested to try use it with no script first because debug was saying it's problem on subliminal site. That time I had problem until I changed password that's why I think that problem with reading password is on subminal site or even provider. 
But you know I can be wrong

**Comment by akash-258** [comment]
This worked for me https://github.com/Diaoul/subliminal/issues/1044#issuecomment-1015226261
